server:
  port: 6012
spring:
  application:
    name: comm-image-service
  datasource:
    url: jdbc:mysql://47.100.97.46:3306/community_sms?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: 47.100.97.46
    port: 6379

aliyunoss:
  accessKeyId: LTAIfW0CYN0Iivbc # 你自己的accessKeyId
  accessKeySecret: sCRdaq7C73dzAQdkG9lY9AFPresdZQ # 你自己的AccessKeySecret
  endpoint: oss-cn-hangzhou.aliyuncs.com
  bucketName: hcq0510


eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/eureka/
